spring.application.name=backprojetobichofull
spring.datasource.url=jdbc:mysql://localhost:3306/bichofull?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=bichofull
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ACESSO_CHAVE_TESTE_PROJETO_BICHOFULL_2026